### ISSUE TITLE
Abstract yazısı kaldırma.

### ISSUE THREAD

**Issue by CelciusZ** [MGokcayK/kou-fbe-latex-tez#1]
tex.tex dosyasında aşağıdaki girdiler kullanıldığında pdfteki sayfanın en üstünde "LATEX FOR WRITING THESIS" şeklinde bir yazı çıkıyor. Bunu nasıl kaldırabiliriz? 

\input{bolumler/abstract.tex}
\createabstract

**Comment by MGokcayK** [comment]
Merhaba, bahsettiğiniz bölüm tezin ingilizce özetinin bulunduğu sayfa ile ilgili olduğunu anlıyorum. "LATEX FOR WRITING THESIS" başlığı repoda bulunan örnek yazının (yazı ayrı zamanda klavuzdur) ingilizce başlığından gelmektedir. Eğer tez.tex içerisindeki 

`% İngilizce başlık
\thetitle{Latex for Writing Thesis}
`

bölümünü kendi başlığınıza uygun olarak değiştirirseniz orası otomatik olarak güncellenecektir. 

Hatırladığım kadarıyla tez yazım kılavuzunda "abstract" bölümünde başlıksız yazı yazılamamaktadır. Dolayısıyla başlığı kaldırmanın yazım kurallarına uygun olduğunu düşünmemekteyim. Eğer kaldırmak isterseniz "kou.cls" adlı dosya içerisindeki 
`	\textbf{\MakeUppercase{\titleng}}`
satırını silmelisiniz.

**Comment by CelciusZ** [comment]
Size yazdıktan hemen sonra halletmiş bulundum. Yine de cevap için teşekkürler. Başka sorum var ama başka başlıkta soracağım. İyi çalışmalar.
